styles:
  content:
    defaultHeaderType: 3
    textmedia:
      linkWrap:
        lightboxEnabled: true
      #maxW: 600
      #maxWInText: 300
      #columnSpacing: 10
      #rowSpacing: 10
      #textMargin: 10
      #borderColor: '#000000'
      #borderWidth: 2
      #borderPadding: 0
      #linkWrap.width: '800m'
      #linkWrap.height: '600m'
  templates:
    templateRootPath: EXT:chf_base/Resources/Private/Templates/FluidStyledContent/Templates/
    partialRootPath: EXT:chf_base/Resources/Private/Templates/FluidStyledContent/Partials/
    layoutRootPath: EXT:chf_base/Resources/Private/Templates/FluidStyledContent/Layouts/