settings:
  chf.templates.path:
    label: 'Template path'
    description: 'Path to a page-view template structure for overrides of CHF templates'
    type: string
    default: ''
  chf.templates.logo.main:
    label: 'Logo path'
    description: 'Path to a logo file to use in the footer of a page'
    type: string
    default: 'EXT:chf_base/Resources/Public/Images/logo-chf-main.svg'
  chf.templates.logo.small:
    label: 'Small logo path'
    description: 'Path to a small logo file to use in the header of a page'
    type: string
    default: 'EXT:chf_base/Resources/Public/Images/logo-chf-small.svg'
  chf.templates.favicon.main:
    label: 'Favicon path'
    description: 'Path to an icon file to use as the favicon of a page'
    type: string
    default: 'EXT:chf_base/Resources/Public/Images/favicon-main.svg'
  chf.templates.favicon.mask:
    label: 'Masked favicon path'
    description: 'Path to an icon file to use as the masked favicon of a page'
    type: string
    default: 'EXT:chf_base/Resources/Public/Images/favicon-mask.svg'
  chf.templates.favicon.app:
    label: 'App favicon path'
    description: 'Path to an icon file to use as the app favicon of a page'
    type: string
    default: 'EXT:chf_base/Resources/Public/Images/favicon-app.png'
  chf.templates.color.highlight:
    label: 'Highlight color'
    description: 'Hex code of the highlight color'
    type: color
    default: '#b21527'
  chf.templates.serviceFolder:
    label: 'Service folder'
    description: 'Page ID of a folder that contains service content like a privacy page'
    type: int
    default: 0
  chf.templates.apiPage:
    label: 'API page'
    description: 'Page ID that contains information about available APIs like REST and SPARQL'
    type: int
    default: 0
  chf.search.pages:
    label: 'Search page IDs'
    description: 'List of page IDs that contain faceted search options'
    type: stringlist
    default: []
  chf.search.examples:
    label: 'Sample searches'
    description: 'List of exemplary search terms to show users as guidance'
    type: stringlist
    default: []
  chf.rights.uri:
    label: 'Rights statement'
    description: 'Default rights statement or license URI for regular page content'
    type: string
    default: 'http://rightsstatements.org/vocab/InC/1.0/'
  chf.citation.style:
    label: 'Citation style'
    description: 'Title of the citation style to apply to sample citations'
    type: string
    default: 'mla-author-title' # 'mla-author-year'
  chf.citation.publisher:
    label: 'Publisher'
    description: 'Name of the publisher to use in sample citations'
    type: string
    default:
  chf.partners.urls:
    label: 'Partner URLs'
    description: 'List of partner URLs to link to in the footer'
    type: stringlist
    default: []
  chf.partners.logos:
    label: 'Partner logos'
    description: 'List of paths to partner logo files to show in the footer'
    type: stringlist
    default: []
  chf.partners.names:
    label: 'Partner names'
    description: 'List of partner names given as labels in the footer'
    type: stringlist
    default: []
  chf.socials.mastodon:
    label: 'Mastodon social account'
    description: 'URL of a profile on Mastodon'
    type: string
    default:
  chf.socials.linkedin:
    label: 'LinkedIn social account'
    description: 'URL of a profile on LinkedIn'
    type: string
    default:
  chf.socials.instagram:
    label: 'Instagram social account'
    description: 'URL of a profile on Instagram'
    type: string
    default:
  chf.socials.facebook:
    label: 'Facebook social account'
    description: 'URL of a profile on Facebook'
    type: string
    default:
  chf.socials.bluesky:
    label: 'Bluesky social account'
    description: 'URL of a profile on Bluesky'
    type: string
    default:
  chf.socials.xitter:
    label: 'X social account'
    description: 'URL of a profile on X'
    type: string
    default:
  chf.socials.gitlab:
    label: 'GitLab social account'
    description: 'URL of a profile on GitLab'
    type: string
    default:
  chf.socials.github:
    label: 'GitHub social account'
    description: 'URL of a profile on GitHub'
    type: string
    default: