name: Publish documentation

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Render documentation
        uses: TYPO3-Documentation/gh-render-action
        id: rendering
      - name: Publish archive with result
        uses: actions/upload-artifact
        with:
          name: Rendered
          path: ${{ steps.rendering.outputs.renderedPath }}

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: Rendered
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages
